### ISSUE TITLE
_xyy and its ilk aren't legal lenses

### ISSUE THREAD

**Issue by ekmett** [lukexi/linear-extra#1]
You could switch them to Getters though and they'd serve all your practical usecases.

**Comment by lukexi** [comment]
Thanks Ed! Fixed.

Let me know if you start playing with Vive stuff, would love to help out : )

**Comment by ekmett** [comment]
I'm starting to play with it on windows. I have 3-4 little projects in
mind. I'm open to a bit more standard windows development and a little less
Haskell purity in my project though, so I'm not sure where the haskell/c++
dividing line will be drawn in my toy projects.

We should chat some time though!

-Edward
